# Generated by Django 3.2.11 on 2022-01-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletime',
            name='schedule_time',
            field=models.TimeField(),
        ),
    ]
