# Generated by Django 3.2.11 on 2022-01-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_scheduletime_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletime',
            name='schedule_time',
            field=models.DateTimeField(),
        ),
    ]
