# Generated by Django 3.2.11 on 2022-01-12 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_scheduletime_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletime',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
